// frontend/vue/src/pages/RecordsPage.vue
<script setup lang="ts">
import TableComponent, { type TableColumn } from '@/components/TableComponent.vue';
import MainLayout from '@/layouts/MainLayout.vue';
import RecordsService, { type TimesheetsRecord } from '@/services/records.service';
import { useRouter } from 'vue-router';
import { ref } from 'vue';

const router = useRouter();
const recordsService = new RecordsService();
const records = ref<Array<TimesheetsRecord>>([]);
const mappedRecords = ref<Record<string, string>[]>([]);

function goToCreate() {
  router.push('/record-create');
}

const columns: Array<TableColumn> = [
  {
    label: 'ID',
    attribute: 'id',
  },
  {
    label: 'Date',
    attribute: 'date',
  },
  {
    label: 'Minutes',
    attribute: 'minutes',
  },
  {
    label: 'Comment',
    attribute: 'comment',
  },
];
records.value = await recordsService.getAllRecords();
mappedRecords.value = records.value.map(r => ({
  'id': `${r.id}`,
  'user_id': `${r.user_id}`,
  'date': r.date,
  'minutes': `${r.minutes}`,
  'comment': r.comment,
}));

async function deleteRecord(index: number) {
  const recordId = records.value[index]?.id;
  if (recordId) {
    const result = await recordsService.deleteRecord(recordId);
    if (result) {
      records.value = await recordsService.getAllRecords();
      mappedRecords.value = records.value.map(r => ({
        'id': `${r.id}`,
        'user_id': `${r.user_id}`,
        'date': r.date,
        'minutes': `${r.minutes}`,
        'comment': r.comment,
      }));
    }
  }
}

function goToUpdatePage(index: number) {
  const recordId = records.value[index]?.id;
  router.push('/record-update/' + recordId);
}
</script>
<template>
  <main-layout>
    <div class="flex flex-col">
      <div class="flex">
        <div class="uppercase cursor-pointer p-2 bg-gray-100 rounded-2xl"
          @click="goToCreate()"
        >Create</div>
      </div>
      <table-component 
        :columns="columns"
        :rows="mappedRecords"
        :delete-button="true"
        :update-button="true"
        @update="goToUpdatePage"
        @delete="deleteRecord"
      />
    </div>
  </main-layout>
</template>

// frontend/react/src/pages/RecordsPage.tsx
import type { TableColumn } from "../components/TableComponent";
import { useState, useEffect } from 'react';
import TableComponent from "../components/TableComponent";
import RecordsService, { type TimesheetsRecord } from "../services/records.service";
import { useNavigate } from "react-router";
import MainLayout from "../layouts/MainLayout";

const recordsService = new RecordsService();
const columns: Array<TableColumn> = [
  {
    label: 'ID',
    attribute: 'id',
  },
  {
    label: 'Date',
    attribute: 'date',
  },
  {
    label: 'Minutes',
    attribute: 'minutes',
  },
  {
    label: 'Comment',
    attribute: 'comment',
  },
];

export default function RecordsPage() {
  const navigate = useNavigate();
  const [records, setRecords] = useState<TimesheetsRecord[]>([]);
  const mapRecords = (records: TimesheetsRecord[]): Record<string, string>[] => {
      return records.map(r => ({
      'id': `${r.id}`,
      'user_id': `${r.user_id}`,
      'date': r.date,
      'minutes': `${r.minutes}`,
      'comment': r.comment,
    }));
  };
  const [rows, setRows] = useState<Record<string, string>[]>([]);
  
  useEffect(() => {
    let isMounted = true; 
    const onInit = async (): Promise<void> => {
      if (isMounted) {
        const result = await recordsService.getAllRecords();
        setRecords(result);
        setRows(mapRecords(result));
      }
    };

    onInit();

    return () => {
      isMounted = false;
    }
  }, []);

  const deleteRecord = async (index: number): Promise<void> => {
    if (await recordsService.deleteRecord(records[index].id)) {
      const records = await recordsService.getAllRecords();
      setRecords(records);
      setRows(mapRecords(records));
    }
  }

  const updateRecord = (index: number): void => {
    navigate(`/record-update/${records[index].id}`);
  }


  const goToCreate = (): void => {
    navigate('/record-create');
  }

  return (
    <MainLayout>
      <div className="flex flex-col">
        <div className="flex">
          <div className="uppercase cursor-pointer p-2 bg-gray-100 rounded-2xl"
            onClick={goToCreate}
          >Create</div>
        </div>
        <TableComponent 
          columns={columns} 
          rows={rows}
          onDelete={deleteRecord}
          onUpdate={updateRecord}
        />
      </div>
    </MainLayout>
  );
}
