// frontend/angular/src/app/pages/RecordCreate/RecordCreate.page.ts
import { Component, inject, signal, WritableSignal } from "@angular/core";
import { MainLayout } from "../../layouts/Main/Main.layout";
import { RecordForm } from "../../components/RecordForm/RecordForm.component";
import RecordsService from "../../services/records.service";
import { Router } from "@angular/router";

@Component({
  selector: 'RecordCreatePage',
  templateUrl: './RecordCreate.page.html',
  imports: [MainLayout, RecordForm],
})
export class RecordCreatePage {
  private readonly recordsService = inject(RecordsService);
  private readonly router = inject(Router);

  minutes: WritableSignal<string> = signal('1');
  date: WritableSignal<string> = signal('');
  comment: WritableSignal<string> = signal('');

  async onCreate() {
    const result = await this.recordsService.createRecord({minutes: Number(this.minutes()), date: this.date(), comment: this.comment()});
    if (result)
      this.router.navigate(['/timetable']);
    else
      alert('Record creation failure.');
  }
}

// frontend/react/src/pages/RecordCreatePage.tsx
import { useNavigate } from "react-router";

import RecordForm from "../components/RecordForm";
import MainLayout from "../layouts/MainLayout";
import RecordsService from "../services/records.service";

const recordsService = new RecordsService();

export default function RecordCreatePage() {
  const navigate = useNavigate();

  const createRecord = async (minutes: string, date: string, comment: string): Promise<void> => {
    const result = await recordsService.createRecord({minutes: Number(minutes), date, comment});
    if (result)
      navigate('/records');
  }
  
  return (
    <MainLayout>
      <div className="grid place-items-center h-screen">
        <RecordForm 
          type="create"
          onSubmit={createRecord}  
        />
      </div>
    </MainLayout>
  )
}
