// frontend/vue/src/pages/SigninPage.vue
<script setup lang="ts">
import UnauthorizedLayout from '@/layouts/UnauthorizedLayout.vue';
import SigninForm from '@/components/SigninForm.vue';
</script>
<template>
  <unauthorized-layout>
    <div class="grid place-items-center h-screen">
      <signin-form />
    </div>
  </unauthorized-layout>
</template>

// frontend/react/src/pages/SigninPage.tsx
import SigninForm from "../components/SigninForm";
import UnauthorizedLayout from "../layouts/UnauthorizedLayout";

export default function SigninPage() {
  return (
    <UnauthorizedLayout>
      <div className="grid place-items-center h-screen">
        <SigninForm />
      </div>
    </UnauthorizedLayout>
  )
}
