// frontend/react/src/components/RecordForm.tsx
import { useState } from "react";
import { NavLink } from "react-router";

import InputComponent from "./InputComponent";

interface onSubmitCallback {
  (minutes: string, date: string): void;
}

interface RecordFormComponentProps {
  type: 'create' | 'update';
  onSubmit?: onSubmitCallback;
} 


export default function RecordForm({type = 'create', onSubmit}: RecordFormComponentProps) {
  const [minutes, setMinutes] = useState('');
  const onMinutesChange = (value: string) => {
    setMinutes(value);
  }
  const [date, setDate] = useState('');
  const onDateChange = (value: string) => {
    setDate(value);
  }
  
  return (
    <div className="bg-gray-200 rounded-2xl p-4 flex flex-col gap-4 items-center">
      <div>Record</div>
      <InputComponent 
        label="Date"
        type="date"
        onInputChange={onDateChange}  
      />
      <InputComponent 
        label="Minutes"
        type="number"
        onInputChange={onMinutesChange}  
      />
      <button 
        className="bg-green-300 rounded-2xl px-2 uppercase"
        onClick={() => {if (onSubmit) onSubmit(minutes, date)}}
      >{ type === 'create' ? 'Create' : 'Update'}
      </button>
      <NavLink
        to="/records"
        className="underline"
      >To records
      </NavLink>
    </div>
  )
}

// frontend/angular/src/app/components/RecordForm/RecordForm.component.ts
import { Component, effect, Input, input, output, signal, WritableSignal } from "@angular/core";
import { InputComponent } from "../Input/Input.component";
import { RouterLink } from "@angular/router";

@Component({
  selector: 'RecordForm',
  templateUrl: './RecordForm.component.html',
  imports: [InputComponent, RouterLink],
})
export class RecordForm {
  type = input<'create' | 'update'>('create');
  @Input() minutes: WritableSignal<string> = signal('');
  @Input() date: WritableSignal<string> = signal('');
  submit = output<void>();
}
<div class="bg-gray-200 rounded-2xl p-4 flex flex-col gap-4 items-center">
  <div>{{ type() === 'create' ? 'Create' : 'Update' }} record</div>
  <InputComponent 
    type="number"
    label="Minutes"
    [(value)]="minutes"
  />
  <InputComponent 
    type="date"
    label="Date"
    [(value)]="date"
  />
  <button 
    class="bg-green-300 rounded-2xl px-2 uppercase cursor-pointer"
    (click)="submit.emit()"
  >submit</button>
  <a 
    class="underline"
    [routerLink]="['/records']">
    To records
  </a>
</div>
