// frontend/vue/src/components/SignupForm.vue
<script setup lang="ts">
import { inject, ref } from 'vue'
import InputComponent from './InputComponent.vue';
import type AuthService from '@/services/auth.service.ts';
import { useRouter } from 'vue-router';

const router = useRouter();
const authService: AuthService | undefined = inject('AuthService');

const email = ref('');
const fullname = ref('');
const password = ref('');
const passwordRepeat = ref('');

async function signup() {
  if (authService !== undefined) {
    const result = await authService.signup({
      email: email.value,
      password: password.value,
      fullname: fullname.value, 
    });
    if (result) {
      router.push('/records');
    }
  } else {
    console.error('AuthService injecting error');
  }
}
</script>
<template>
  <div class="bg-gray-200 rounded-2xl p-4 flex flex-col gap-4 items-center">
    <div>Sign up</div>
    <input-component
      label="Email"
      type="email"
      v-model="email"
    />
    <input-component 
      label="Fullname"
      type="text"
      v-model="fullname"
    />
    <input-component 
      label="Password"
      type="password" 
      v-model="password"
    />
    <input-component 
      label="Password repeat"
      type="password" 
      v-model="passwordRepeat"
    />
    <button 
      class="bg-green-300 rounded-2xl px-2 uppercase"
      @click="signup()"
    >submit</button>
    <RouterLink 
      class="underline"
      to="/signin">
      Sign in
    </RouterLink>
  </div>
</template>

// frontend/angular/src/app/components/SignupForm/SignupForm.component.ts
import { Component, inject, signal, Signal } from "@angular/core";
import { InputComponent } from "../Input/Input.component";
import AuthService from "../../services/auth.service";
import { RouterLink } from "@angular/router";

@Component({
  selector: 'SignupForm',
  templateUrl: './SignupForm.component.html',
  imports: [InputComponent, RouterLink],
})
export class SignupForm {
  private readonly authService = inject(AuthService);
  email = signal<string>('');
  password = signal<string>('');
  passwordRepeat = signal<string>('');
  fullname = signal<string>('');

  async signup(): Promise<void> {
    this.authService.signup({
      password: this.password(), 
      email: this.email(),
      fullname: this.fullname(),
    });
  }
}
<div class="bg-gray-200 rounded-2xl p-4 flex flex-col gap-4 items-center">
  <div>Sign in</div>
  <InputComponent 
    type="email"
    label="Email"
    [(value)]="email"
  />
  <InputComponent 
    type="text"
    label="Fullname"
    [(value)]="fullname"
  />
  <InputComponent 
    label="Password"
    type="password" 
    [(value)]="password"
  />
  <InputComponent 
    label="Repeat password"
    type="password" 
    [(value)]="passwordRepeat"
  />
  <button 
    class="bg-green-300 rounded-2xl px-2 uppercase"
    (click)="signup()"
  >submit</button>
  <a 
    class="underline"
    [routerLink]="['/signin']">
    Signin
 </a>
</div>
