// frontend/react/src/components/SignupForm.tsx
import { useState } from "react";
import { useNavigate } from "react-router";
import { NavLink } from "react-router";

import InputComponent from "./InputComponent";
import AuthService from "../services/auth.service";

const authService = new AuthService();

export default function SignupForm() {
  const navigate = useNavigate();
  const [fullname, setFullname] = useState('');
  const onFullnameChange = (value: string) => {
    setFullname(value);
  }
  const [email, setEmail] = useState('');
  const onEmailChange = (value: string) => {
    setEmail(value);
  }
  const [password, setPassword] = useState('');
  const onPasswordChange = (value: string) => {
    setPassword(value);
  }
  const [passwordRepeat, setPasswordRepeat] = useState('');
  const onPasswordRepeatChange = (value: string) => {
    setPasswordRepeat(value);
  }

  const signup = async (): Promise<void>  => {
    if (password !== passwordRepeat) {
      alert("Passwords don't match.");
      return;
    }
    if (await authService.signup({password, email, fullname}))
      navigate('/records');
  }
  
  return (
    <div className="bg-gray-200 rounded-2xl p-4 flex flex-col gap-4 items-center">
      <div>Sign up</div>
      <InputComponent 
        label="Fullname"
        type="text"
        onInputChange={onFullnameChange}  
      />
      <InputComponent 
        label="Email"
        type="email"
        onInputChange={onEmailChange}  
      />
      <InputComponent 
        label="Password"
        type="password"
        onInputChange={onPasswordChange}  
      />
      <InputComponent 
        label="Repeat password"
        type="password"
        onInputChange={onPasswordRepeatChange}  
      />
      <button 
        className="bg-green-300 rounded-2xl px-2 uppercase"
        onClick={signup}
      >submit
      </button>
      <NavLink
        to="/signin"
        className="underline"
      >Signin
      </NavLink>
    </div>
  )
}

// frontend/angular/src/app/components/SignupForm/SignupForm.component.ts
import { Component, inject, signal, Signal } from "@angular/core";
import { InputComponent } from "../Input/Input.component";
import AuthService from "../../services/auth.service";
import { RouterLink } from "@angular/router";

@Component({
  selector: 'SignupForm',
  templateUrl: './SignupForm.component.html',
  imports: [InputComponent, RouterLink],
})
export class SignupForm {
  private readonly authService = inject(AuthService);
  email = signal<string>('');
  password = signal<string>('');
  passwordRepeat = signal<string>('');
  fullname = signal<string>('');

  async signup(): Promise<void> {
    this.authService.signup({
      password: this.password(), 
      email: this.email(),
      fullname: this.fullname(),
    });
  }
}
<div class="bg-gray-200 rounded-2xl p-4 flex flex-col gap-4 items-center">
  <div>Sign in</div>
  <InputComponent 
    type="email"
    label="Email"
    [(value)]="email"
  />
  <InputComponent 
    type="text"
    label="Fullname"
    [(value)]="fullname"
  />
  <InputComponent 
    label="Password"
    type="password" 
    [(value)]="password"
  />
  <InputComponent 
    label="Repeat password"
    type="password" 
    [(value)]="passwordRepeat"
  />
  <button 
    class="bg-green-300 rounded-2xl px-2 uppercase"
    (click)="signup()"
  >submit</button>
  <a 
    class="underline"
    [routerLink]="['/signin']">
    Signin
 </a>
</div>
