// frontend/react/src/pages/RecordUpdatePage.tsx
import { useNavigate, useParams } from "react-router";
import { useEffect, useState } from "react";

import RecordForm from "../components/RecordForm";
import MainLayout from "../layouts/MainLayout";
import RecordsService, { type TimesheetsRecord } from "../services/records.service";

const recordsService = new RecordsService();

export default function RecordUpdatePage() {
  const navigate = useNavigate();
  const {id} = useParams();
  const [record, setRecord] = useState<TimesheetsRecord | null>(null);
  useEffect(() => {
    let isMounted = true; 
    const onInit = async (): Promise<void> => {
      if (isMounted) {
        const result = await recordsService.getRecord(Number(id));
        setRecord(result);
      }
    };

    onInit();

    return () => {
      isMounted = false;
    }
  }, []);

  const updateRecord = async (minutes: string, date: string, comment: string): Promise<void> => {
    const result = await recordsService.updateRecord({
      minutes: Number(minutes),
      date,
      recordId: Number(id),
      comment,
    });
    if (result)
      navigate('/records');
  }
  
  return (
    <MainLayout>
      <div className="grid place-items-center h-screen">
        <RecordForm 
          type="update"
          onSubmit={updateRecord}
          minutesInitial={record?.minutes}
          dateInitial={record?.date}
          commentInitial={record?.comment}
        />
      </div>
    </MainLayout>
  )
}

// frontend/angular/src/app/pages/RecordUpdate/RecordUpdate.page.ts
import { Component, inject, OnInit, signal, WritableSignal } from "@angular/core";
import { ActivatedRoute, Router } from "@angular/router";
import { MainLayout } from "../../layouts/Main/Main.layout";
import { RecordForm } from "../../components/RecordForm/RecordForm.component";
import RecordsService, { TimesheetsRecord } from "../../services/records.service";

@Component({
  selector: 'RecordUpdatePage',
  templateUrl: './RecordUpdate.page.html',
  imports: [MainLayout, RecordForm],
})
export class RecordUpdatePage implements OnInit {
  private readonly recordsService = inject(RecordsService);
  private readonly router = inject(Router);
  private readonly route = inject(ActivatedRoute);

  minutes: WritableSignal<string> = signal('1');
  date: WritableSignal<string> = signal('');
  comment: WritableSignal<string> = signal('');
  private id: number = 0;
  private record: TimesheetsRecord | null = null

  constructor() {
    this.id = Number(this.route.snapshot.paramMap.get('id'));
  }

  async ngOnInit(): Promise<void> {
    this.record = await this.recordsService.getRecord(this.id);
    if (this.record) {
      this.minutes.set(String(this.record?.minutes));
      this.date.set(String(this.record?.date));
      this.comment.set(String(this.record?.comment));
    }
  }

  async onUpdate() {
    const result = await this.recordsService.updateRecord({
      recordId: this.id,
      minutes: Number(this.minutes()), 
      date: this.date(),
      comment: this.comment(),
    });
    if (result)
      this.router.navigate(['/records']);
    else
      alert('Record update failure.');
  }
}
