// frontend/angular/src/app/components/SigninForm/SigninForm.component.ts
import { Component, inject, signal, Signal } from "@angular/core";
import { InputComponent } from "../Input/Input.component";
import AuthService from "../../services/auth.service";
import { RouterLink } from "@angular/router";

@Component({
  selector: 'SigninForm',
  templateUrl: './SigninForm.component.html',
  imports: [InputComponent, RouterLink],
})
export class SigninForm {
  private readonly authService = inject(AuthService);
  email = signal<string>('');
  password = signal<string>('');

  async login(): Promise<void> {
    this.authService.signin(this.password(), this.email());
  }
}
<div class="bg-gray-200 rounded-2xl p-4 flex flex-col gap-4 items-center">
  <div>Sign in</div>
  <InputComponent 
    type="email"
    label="Email"
    [(value)]="email"
  />
  <InputComponent 
    label="Password"
    type="password" 
    [(value)]="password"
  />
  <button 
    class="bg-green-300 rounded-2xl px-2 uppercase"
    (click)="login()"
  >submit</button>
  <a 
    class="underline"
    [routerLink]="['/signup']">
    Signup
 </a>
</div>

// frontend/vue/src/components/SigninForm.vue
<script setup lang="ts">
import { inject, ref } from 'vue'
import InputComponent from './InputComponent.vue';
import type AuthService from '@/services/auth.service.ts';
import { useRouter } from 'vue-router';

const router = useRouter();
const authService: AuthService | undefined = inject('AuthService');

const email = ref('');
const password = ref('');

async function login() {
  if (authService !== undefined) {
    const result = await authService.signin(password.value, email.value);
    if (result) {
      router.push('/');
    }
  } else {
    console.error('AuthService injecting error');
  }
}
</script>
<template>
  <div class="bg-gray-200 rounded-2xl p-4 flex flex-col gap-4 items-center">
    <div>Sign in</div>
    <input-component 
      type="email"
      label="Email"
      v-model:value="email"
    />
    <input-component 
      label="Password"
      type="password" 
      v-model:value="password"
    />
    <button 
      class="bg-green-300 rounded-2xl px-2 uppercase"
      @click="login()"
    >submit</button>
    <RouterLink 
      class="underline"
      to="/signup">
      Signup
    </RouterLink>
  </div>
</template>
