// frontend/react/src/components/TextareaComponent.tsx
import { v4 as uuidv4 } from 'uuid';

interface onTextareaChangeCallback {
  (value: string): void
}

interface TextareaComponentProps {
  label?: string;
  value: string;
  onChange: onTextareaChangeCallback;
} 

export default function TextareaComponent({label, onChange, value} : TextareaComponentProps) {
  const id = uuidv4();

  return (
    <div className='flex flex-col'>
      { label && <label className='pl-2' htmlFor={id}>{label}</label>}
      
      <textarea 
        id={id}
        className='bg-white rounded-2xl px-2' 
        value={value}
        onChange={e => onChange(e.target.value)}  
      ></textarea>
    </div>
  )
}

// frontend/vue/src/components/TextareaComponent.vue
<script setup lang="ts">
import {v4 as uuidv4} from 'uuid';

interface Props {
  label?: string
}
const props = defineProps<Props>();
const id = uuidv4();
const value = defineModel({ 
  required: false, 
  default: '' 
});
</script>
<template>
  <div class="flex flex-col">
    <label
      class="pl-2" 
      :for="id">{{ props.label || '' }}</label>
    <textarea 
      class="bg-white rounded-2xl px-2"
      :id="id"
      v-model="value"
    ></textarea>
  </div>
</template>
