// frontend/angular/src/app/components/Input/Input.component.ts
import { Component, input, output } from "@angular/core";
import { v4 as uuidv4 } from 'uuid';


@Component({
  selector: 'InputComponent',
  templateUrl: './Input.component.html',
})
export class InputComponent {
  type = input<'text' | 'password' | 'email' | 'date' | 'number'>('text');
  label = input<string>('');
  input = output<string>();
  id = uuidv4();

  onInput(event: InputEvent) {
    event.stopPropagation(); 
    const element = event.target as HTMLInputElement;
    this.input.emit(String(element.value));
  }
}
<div class="flex flex-col">
  <label
    class="pl-2" 
    [for]="id">{{ label() || '' }}</label>
  <input 
    class="bg-white rounded-2xl px-2"
    [id]="id"
    [type]="type()"
    (input)="onInput($event)"
  >
</div>

// frontend/react/src/components/InputComponent.tsx
import { useEffect, useState } from 'react';
import { v4 as uuidv4 } from 'uuid';

interface onInputChangeCallback {
  (value: string): void
}

interface InputComponentProps {
  label?: string;
  type: 'text' | 'password' | 'email' | 'number' | 'date';
  initialValue?: string;
  onInputChange: onInputChangeCallback;
} 

export default function InputComponent({label, type = 'text', onInputChange, initialValue = ''} : InputComponentProps) {
  const id = uuidv4();
  const [value, setValue] = useState(initialValue);
  useEffect(() => {
    setValue(initialValue)
  }, [initialValue]);
  const handleInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setValue(event.target.value);
    onInputChange(event.target.value);
  };

  return (
    <div className='flex flex-col'>
      { label && <label className='pl-2' htmlFor={id}>{label}</label>}
      
      <input 
        id={id}
        className='bg-white rounded-2xl px-2' 
        type={type} 
        value={value}
        onChange={handleInputChange}  
      />
    </div>
  )
}
