// frontend/vue/src/components/TableComponent.vue
<script setup lang="ts">
import { Pencil, Trash } from '@lucide/vue';
import { computed } from 'vue';

export interface TableColumn {
  label: string, 
  attribute: string,
};
interface Props {
  columns: Array<TableColumn>,
  rows: Array<Record<string, string>>,
  deleteButton: boolean,
  updateButton: boolean,
};
const props = defineProps<Props>();
const emit = defineEmits(['delete', 'update']);
const colspan = computed(() => {
  const rowsCount = props.rows.length;
  const actionButtonPresent = props.deleteButton || props.updateButton;

  return rowsCount + (actionButtonPresent ? 1 : 0);
});
</script>
<template>
<div class="w-full overflow-x-scroll">
  <table class="w-full min-w-[600px] py-2"
    v-if="props.columns.length">
    <thead>
      <tr>
        <th scope="col" v-for="col in props.columns" :key="col.attribute">{{ col.label || ''}}</th>
        <th scope="col" v-if="props.deleteButton || props.updateButton">Actions</th>
      </tr>
    </thead>
    <tbody v-if="props.rows.length" >
      <tr v-for="(row, index) in props.rows" :key="index">
        <td v-for="col in props.columns" :key="col.attribute">
           {{ row[col.attribute] || '' }}
        </td>
        <td v-if="props.updateButton || props.deleteButton">
          <div
            class="flex gap-2 w-full justify-center">
            <Pencil 
              class="cursor-pointer"
              v-if="props.updateButton"
              @click="emit('update', index)"  
            />            
            <Trash 
              class="cursor-pointer"
              v-if="props.deleteButton"
              @click="emit('delete', index)"
              />
          </div>
        </td>
      </tr>
    </tbody>
    <tbody v-else>
      <tr>
        <td :colspan="colspan">No data</td>
      </tr>
    </tbody>
  </table>
</div>
</template>
<style>
th, td {
  text-align: center;
}
</style>

// frontend/react/src/components/TableComponent.tsx
import { Pencil, Trash } from 'lucide-react';
import './TableComponent.css';
import { useEffect, useState } from 'react';

interface onActionCallback {
  (id: number): void;
}

export interface TableColumn {
  label: string; 
  attribute: string;
}

interface TableComponentProps {
  columns?: TableColumn[];
  rows?: Record<string, string>[];
  openObjectPageColumnAttribute?: string;
  onDelete?: onActionCallback;
  onUpdate?: onActionCallback;
  onOpen?: onActionCallback;
} 

export default function TableComponent({onDelete, onUpdate, onOpen, columns = [], rows = [], openObjectPageColumnAttribute = ''}: TableComponentProps) {  
  const [colspan, setColspan] = useState(columns.length + (onDelete || onUpdate ? 1 : 0));
  useEffect(() => {
    setColspan(columns.length + (onDelete || onUpdate ? 1 : 0));
  }, [rows, onDelete, onUpdate]);

  return columns.length && 
  <div className="w-full overflow-auto">
    <table className='w-full min-w-[600px] py-2'>{
      <thead>
        <tr>
          { columns.map(c => 
            <th key={c.attribute}>{c.label}</th>)
          }
          { (onUpdate || onDelete) && <th key='actions'>Actions</th>}
        </tr>
      </thead>}
      <tbody>
      {rows.map((r, i) => <tr key={i}>
        {columns.map(c =>  c.attribute === openObjectPageColumnAttribute ? 
        <td key={c.attribute}>
          <div 
            className='underline cursor-pointer'
            onClick={() => onOpen ? onOpen(i) : {}}  
          >{r[c.attribute]}</div>
        </td>  :
        <td key={c.attribute}>{r[c.attribute]}</td>
      )}
        {<td key='actions'>
          <div className='flex gap-2 w-full justify-center'>
            { onUpdate && <div className='underline cursor-pointer' onClick={() => onUpdate(i)}>Update</div> }
            { onDelete && <div className='underline cursor-pointer' onClick={() => onDelete(i)}>Delete</div> }
          </div>
        </td>}
      </tr>)}
      { !rows.length && <tr><td colSpan={colspan}>No data</td></tr>}
      </tbody>
    </table>
  </div>;
}
