// frontend/angular/src/app/components/Textarea/Textarea.component.ts
import { Component, input, model, output } from "@angular/core";
import { v4 as uuidv4 } from 'uuid';


@Component({
  selector: 'TextareaComponent',
  templateUrl: './Textarea.component.html',
})
export class TextareaComponent {
  label = input<string>('');
  id = uuidv4();
  value = model<string>('');

  onInput(event: InputEvent) {
    event.stopPropagation(); 
    const element = event.target as HTMLTextAreaElement;
    const newValue = element.value;
    this.value.set(newValue);
  }
}
<div class="flex flex-col">
  <label
    class="pl-2" 
    [for]="id">{{ label() || '' }}</label>
  <textarea 
    class="bg-white rounded-2xl px-2"
    [id]="id"
    [value]="value()"
    (input)="onInput($event)"
  ></textarea>
</div>

// frontend/react/src/components/TextareaComponent.tsx
import { useState } from 'react';
import { v4 as uuidv4 } from 'uuid';

interface onTextareaChangeCallback {
  (value: string): void
}

interface TextareaComponentProps {
  label?: string;
  initialValue?: string;
  onChange: onTextareaChangeCallback;
} 

export default function TextareaComponent({label, onChange, initialValue = ''} : TextareaComponentProps) {
  const id = uuidv4();
  const [value, setValue] = useState(initialValue);
  const handleInputChange = (event: React.ChangeEvent<HTMLTextAreaElement>) => {
    setValue(event.target.value);
    onChange(event.target.value);
  };

  return (
    <div className='flex flex-col'>
      { label && <label className='pl-2' htmlFor={id}>{label}</label>}
      
      <textarea 
        id={id}
        className='bg-white rounded-2xl px-2' 
        value={value}
        onChange={handleInputChange}  
      ></textarea>
    </div>
  )
}
