// frontend/vue/src/pages/SignupPage.vue
<script setup lang="ts">
import UnauthorizedLayout from '@/layouts/UnauthorizedLayout.vue';
import SignupForm from '@/components/SignupForm.vue';
</script>
<template>
  <unauthorized-layout>
    <div class="grid place-items-center h-screen">
      <signup-form />
    </div>
  </unauthorized-layout>
</template>

// frontend/angular/src/app/pages/Signup/Signup.page.ts
import { Component } from "@angular/core";
import { UnauthorizedLayout } from "../../layouts/Unauthorized/Unauthorized.layout";
import { SignupForm } from "../../components/SignupForm/SignupForm.component";

@Component({
  selector: 'SignupPage',
  templateUrl: './Signup.page.html',
  imports: [UnauthorizedLayout, SignupForm]
})
export class SignupPage {

}
