// frontend/angular/src/app/pages/Project/Project.page.ts
import { Component, inject, OnInit, signal, WritableSignal } from "@angular/core";
import { MainLayout } from "../../layouts/Main/Main.layout";
import { ActivatedRoute, Router, RouterLink } from "@angular/router";
import ProjectsService, { TimesheetsProject } from "../../services/projects.service";
import { TableColumn, TasksTableComponent } from "../../components/TasksTableComponent/TasksTableComponent.component";
import TasksService, { TimesheetsTask } from "../../services/tasks.service";
import { minutesToString } from "../../utils/time";

@Component({
  selector: 'ProjectPage',
  templateUrl: './Project.page.html',
  imports: [MainLayout, RouterLink, TasksTableComponent],
})
export class ProjectPage {
  private readonly router = inject(Router);
  private readonly projectsService = inject(ProjectsService);
  private readonly tasksService = inject(TasksService);
  private readonly route = inject(ActivatedRoute);

  private project: TimesheetsProject | null = null;
  id: number = 0;

  title: WritableSignal<string> = signal('');
  code: WritableSignal<string> = signal('');
  description: WritableSignal<string> = signal('');

  columns: Array<TableColumn> = [
    {
      label: 'Title',
      attribute: 'title',
    },
    {
      label: 'Code',
      attribute: 'code',
    },
    {
      label: 'Description',
      attribute: 'description',
    },
    {
      label: 'Spent time',
      attribute: 'total_minutes',
    },
  ];
  private tasks: TimesheetsTask[] = [];
  mappedTasks: WritableSignal<Record<string, string>[]> = signal([]);

  constructor() {
    this.id = Number(this.route.snapshot.paramMap.get('id'));
  }

  async ngOnInit(): Promise<void> {
    this.project = await this.projectsService.get(this.id);
    if (this.project) {
      this.title.set(String(this.project?.title));
      this.code.set(String(this.project?.code));
      this.description.set(String(this.project?.description));
      await this.refreshTasks();
    }
  }


  private async refreshTasks(): Promise<void> {
    this.tasks = await this.tasksService.getAllForProject(this.id);
    this.mappedTasks.set(this.tasks.map(r => ({
      'id': `${r.id}`,
      'user_id': `${r.user_id}`,
      'title': r.title,
      'description': r.description,
      'code': r.code,
      'total_minutes': r.total_minutes ? minutesToString(r.total_minutes) : '',
    })));
  }

  goToUpdateTaskPage(index: number) {
    const id = this.tasks[index]?.id;
    this.router.navigate(['/task/' + id + '/update']);
  }

  async deleteTask(index: number) {
    const id = this.tasks[index]?.id;
    if (id) {
      const result = await this.tasksService.delete(id);
      if (result) {
        await this.refreshTasks();
      }
    }
  }

  goToTask(index: number) {
    const id = this.tasks[index]?.id;
    this.router.navigate(['/task/' + id]);
  }
}

// frontend/vue/src/pages/ProjectPage.vue
<script setup lang="ts">
import TableComponent, { type TableColumn } from '@/components/TableComponent.vue';
import MainLayout from '@/layouts/MainLayout.vue';
import { useRoute, useRouter } from 'vue-router';
import { ref } from 'vue';
import ProjectsService from '@/services/projects.service';
import { minutesToString } from '@/utils/time';
import  TasksService, { type TimesheetsTask } from '@/services/tasks.service';

const router = useRouter();
const route = useRoute();
const projectId = Number(route.params.id);
const projectsService = new ProjectsService();
const project = await projectsService.get(projectId);
const title = ref(project?.title || '');
const code = ref(project?.code || '');
const description = ref(project?.description || '');
const tasksService = new TasksService();
const tasks = ref<Array<TimesheetsTask>>([]);
const mappedTasks = ref<Record<string, string>[]>([]);

const columns: Array<TableColumn> = [
  {
    label: 'Title',
    attribute: 'title',
  },
  {
    label: 'Code',
    attribute: 'code',
  },
  {
    label: 'Description',
    attribute: 'description',
  },
  {
    label: 'Spent time',
    attribute: 'total_minutes',
  },
];

tasks.value = await tasksService.getAllForProject(projectId);
mappedTasks.value = tasks.value.map(t => ({
  'id': `${t.id}`,
  'user_id': `${t.user_id}`,
  'title': t.title,
  'code': t.code,
  'description': t.description,
  'total_minutes': minutesToString(t.total_minutes || 0),
}));

async function deleteTask(index: number) {
  const id = tasks.value[index]?.id;
  if (id) {
    const result = await tasksService.delete(id);
    if (result) {
      tasks.value = await tasksService.getAllForProject(projectId);
      mappedTasks.value = tasks.value.map(t => ({
        'id': `${t.id}`,
        'user_id': `${t.user_id}`,
        'title': t.title,
        'code': t.code,
        'description': t.description,
        'total_minutes': minutesToString(t.total_minutes || 0),
      }));
    }
  }
}

function goToUpdatePage(index: number) {
  const id = tasks.value[index]?.id;
  router.push("/project/" + projectId + "/update-task/" + id);
}

</script>
<template>
  <main-layout>
    <div class="flex flex-col gap-8">
      <div class="flex place-items-end gap-4">
        <div class="text-2xl">Project</div>
        <div class="flex place-items-end gap-4">
          <div class="text-2xl">{{ title }}</div>
          <div>({{ code }})</div>
        </div>
      </div>
      <div >{{ description }}</div>
      <RouterLink 
        class="underline"
        :to="'/project/' + projectId + '/create-task'">Create task</RouterLink>
      <table-component 
        :columns="columns"
        :rows="mappedTasks"
        :delete-button="true"
        :update-button="true"
        @update="goToUpdatePage"
        @delete="deleteTask"
      />
    </div>
  </main-layout>
</template>
