// frontend/angular/src/app/pages/Records/Records.page.ts
import { Component, inject, OnInit, signal, WritableSignal } from "@angular/core";
import { MainLayout } from "../../layouts/Main/Main.layout";
import { TableColumn, TableComponent } from "../../components/TableComponent/TableComponent.component";
import { Router } from "@angular/router";
import RecordsService, { TimesheetsRecord } from "../../services/records.service";

@Component({
  selector: 'RecordsPage',
  templateUrl: './Records.page.html',
  imports: [MainLayout, TableComponent],
})
export class RecordsPage implements OnInit {
  private readonly router = inject(Router);
  private readonly recordsService = inject(RecordsService);

  columns: Array<TableColumn> = [
    {
      label: 'ID',
      attribute: 'id',
    },
    {
      label: 'Date',
      attribute: 'date',
    },
    {
      label: 'Minutes',
      attribute: 'minutes',
    },
    {
      label: 'Comment',
      attribute: 'comment',
    },
  ];
  private records: TimesheetsRecord[] = [];
  mappedRecords: WritableSignal<Record<string, string>[]> = signal([]);

  async ngOnInit(): Promise<void> {
    await this.refreshRecords();
  }

  private async refreshRecords(): Promise<void> {
    this.records = await this.recordsService.getAllRecords();
    this.mappedRecords.set(this.records.map(r => ({
      'id': `${r.id}`,
      'user_id': `${r.user_id}`,
      'date': r.date,
      'minutes': `${r.minutes}`,
      'comment': `${r.comment}`,
    })));
  }

  goToCreate() {
    this.router.navigate(['/record-create'])
  }

  goToUpdatePage(index: number) {
    const recordId = this.records[index]?.id;
    this.router.navigate(['/record-update/' + recordId]);
  }

  async deleteRecord(index: number) {
    const recordId = this.records[index]?.id;
    if (recordId) {
      const result = await this.recordsService.deleteRecord(recordId);
      if (result) {
        await this.refreshRecords();
      }
    }
  }
}

// frontend/vue/src/pages/RecordsPage.vue
<script setup lang="ts">
import TableComponent, { type TableColumn } from '@/components/TableComponent.vue';
import MainLayout from '@/layouts/MainLayout.vue';
import RecordsService, { type TimesheetsRecord } from '@/services/records.service';
import { useRouter } from 'vue-router';
import { ref } from 'vue';

const router = useRouter();
const recordsService = new RecordsService();
const records = ref<Array<TimesheetsRecord>>([]);
const mappedRecords = ref<Record<string, string>[]>([]);

function goToCreate() {
  router.push('/record-create');
}

const columns: Array<TableColumn> = [
  {
    label: 'ID',
    attribute: 'id',
  },
  {
    label: 'Date',
    attribute: 'date',
  },
  {
    label: 'Minutes',
    attribute: 'minutes',
  },
  {
    label: 'Comment',
    attribute: 'comment',
  },
];
records.value = await recordsService.getAllRecords();
mappedRecords.value = records.value.map(r => ({
  'id': `${r.id}`,
  'user_id': `${r.user_id}`,
  'date': r.date,
  'minutes': `${r.minutes}`,
  'comment': r.comment,
}));

async function deleteRecord(index: number) {
  const recordId = records.value[index]?.id;
  if (recordId) {
    const result = await recordsService.deleteRecord(recordId);
    if (result) {
      records.value = await recordsService.getAllRecords();
      mappedRecords.value = records.value.map(r => ({
        'id': `${r.id}`,
        'user_id': `${r.user_id}`,
        'date': r.date,
        'minutes': `${r.minutes}`,
        'comment': r.comment,
      }));
    }
  }
}

function goToUpdatePage(index: number) {
  const recordId = records.value[index]?.id;
  router.push('/record-update/' + recordId);
}
</script>
<template>
  <main-layout>
    <div class="flex flex-col">
      <div class="flex">
        <div class="uppercase cursor-pointer p-2 bg-gray-100 rounded-2xl"
          @click="goToCreate()"
        >Create</div>
      </div>
      <table-component 
        :columns="columns"
        :rows="mappedRecords"
        :delete-button="true"
        :update-button="true"
        @update="goToUpdatePage"
        @delete="deleteRecord"
      />
    </div>
  </main-layout>
</template>
