// frontend/angular/src/app/pages/Signin/Signin.page.ts
import { Component } from "@angular/core";
import { UnauthorizedLayout } from "../../layouts/Unauthorized/Unauthorized.layout";
import { SigninForm } from "../../components/SigninForm/SigninForm.component";

@Component({
  selector: 'SigninPage',
  templateUrl: './Signin.page.html',
  imports: [UnauthorizedLayout, SigninForm]
})
export class SigninPage {

}

// frontend/vue/src/pages/SigninPage.vue
<script setup lang="ts">
import UnauthorizedLayout from '@/layouts/UnauthorizedLayout.vue';
import SigninForm from '@/components/SigninForm.vue';
</script>
<template>
  <unauthorized-layout>
    <div class="grid place-items-center h-screen">
      <signin-form />
    </div>
  </unauthorized-layout>
</template>
