// frontend/react/src/pages/SignupPage.tsx
import SignupForm from "../components/SignupForm";
import UnauthorizedLayout from "../layouts/UnauthorizedLayout";

export default function SignupPage() {
  return (
    <UnauthorizedLayout>
      <div className="grid place-items-center h-screen">
        <SignupForm />
      </div>
    </UnauthorizedLayout>
  )
}

// frontend/vue/src/pages/SignupPage.vue
<script setup lang="ts">
import UnauthorizedLayout from '@/layouts/UnauthorizedLayout.vue';
import SignupForm from '@/components/SignupForm.vue';
</script>
<template>
  <unauthorized-layout>
    <div class="grid place-items-center h-screen">
      <signup-form />
    </div>
  </unauthorized-layout>
</template>
