// frontend/vue/src/components/TableComponent.vue
<script setup lang="ts">
import { Pencil, Trash } from '@lucide/vue';

export interface TableColumn {
  label: string, 
  attribute: string,
};
interface Props {
  columns: Array<TableColumn>,
  rows: Array<Record<string, string>>,
  deleteButton: boolean,
  updateButton: boolean,
};
const props = defineProps<Props>();
const emit = defineEmits(['delete', 'update']);
</script>
<template>
  <table 
    class="rounded-2xl"
    v-if="props.columns.length">
    <thead>
      <tr>
        <th scope="col" v-for="col in props.columns" :key="col.attribute">{{ col.label || ''}}</th>
        <th scope="col" v-if="props.deleteButton || props.updateButton">Actions</th>
      </tr>
    </thead>
    <tbody v-if="props.rows.length" >
      <tr v-for="(row, index) in props.rows" :key="index">
        <td v-for="col in props.columns" :key="col.attribute">
           {{ row[col.attribute] || '' }}
        </td>
        <td v-if="props.updateButton || props.deleteButton">
          <div
            class="flex gap-2 w-full justify-center">
            <Pencil 
              class="cursor-pointer"
              v-if="props.updateButton"
              @click="emit('update', index)"  
            />            
            <Trash 
              class="cursor-pointer"
              v-if="props.deleteButton"
              @click="emit('delete', index)"
              />
          </div>
        </td>
      </tr>
    </tbody>
    <tbody v-else>
      <tr>
        <td :colspan="props.columns.length">No data</td>
      </tr>
    </tbody>
  </table>
</template>
<style>
th, td {
  text-align: center;
}
</style>

// frontend/angular/src/app/components/TableComponent/TableComponent.component.ts
import { Component, input, output } from "@angular/core";
import  { LucidePencil, LucideTrash } from '@lucide/angular'

export interface TableColumn {
  label: string, 
  attribute: string,
};

@Component({
  selector: 'TableComponent',
  templateUrl: './TableComponent.component.html',
  styleUrl: './TableComponent.component.css',
  imports: [LucidePencil, LucideTrash],
})
export class TableComponent {
  columns = input<TableColumn[]>([]);
  rows = input<Record<string, string>[]>([]);
  deleteButton = input<boolean>(false);
  updateButton = input<boolean>(false);
  update = output<number>(); 
  delete = output<number>(); 


  onUpdate(index: number) {
    this.update.emit(index);
  }

  onDelete(index: number) {
    this.delete.emit(index);
  }
}
@if(columns().length) {
<table class="rounded-2xl">
    <thead>
      <tr>
        @for (col of columns(); track $index) {
          <th scope="col">{{ col.label || ''}}</th>
        }
        @if(deleteButton() || updateButton()) {
          <th scope="col">Actions</th>
        }
      </tr>
    </thead>
    @if (rows().length) {
    <tbody>
      @for(row of rows(); track $index) {
      <tr>
        @for (col of columns(); track col.attribute) {
        <td>
           {{ row[col.attribute] || '' }}
        </td>
        }
        @if (updateButton() || deleteButton()) {
        <td>
          <div class="flex gap-2 w-full justify-center">
            @if (updateButton()) {
            <svg lucidePencil 
              class="cursor-pointer" 
              [size]="32" color="black" 
              [strokeWidth]="1" 
              title="Update"
              (click)="onUpdate($index)"  
            ></svg>  
            }
            @if (deleteButton()) {
            <svg lucideTrash
              class="cursor-pointer" 
              [size]="32" color="black" 
              [strokeWidth]="1" 
              title="Update"
              (click)="onDelete($index)"  
            ></svg>
            }       
          </div>
        </td>
        }
      </tr>
      }
    </tbody>
    } @else {
    <tbody>
      <tr>
        <td [colSpan]="columns().length">No data</td>
      </tr>
    </tbody>
    }
  </table>
}
