// frontend/react/src/layouts/MainLayout.tsx
import HeaderMenu from "../components/HeaderMenu"

export default function MainLayout(props) {
  return (
    <>
      <HeaderMenu />
      <div className="flex justify-center">
        <div className="justify-between py-2 sm:px-16 max-w-[1920px] w-full">
          <main>
            { props.children }
          </main>
        </div>
      </div>
    </>
  )
}

// frontend/vue/src/layouts/MainLayout.vue
<script setup lang="ts">
import HeaderMenu from '@/components/HeaderMenu.vue';


</script>
<template>
  <header-menu />
    <div class="flex justify-center">
      <div class="justify-between py-2 px-16 max-w-[1920px] w-full">
      <main>
        <slot></slot>
      </main>
    </div>
  </div>
</template>
